[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless-plugin" }
versions = { id = "io.github.ben-manes.versions", version.ref = "versions-plugin" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "catalog-update-plugin" }

[versions]
spotless-plugin = "8.10.1"
versions-plugin = "0.61.0"
catalog-update-plugin = "1.1.1"
junit-bom = "6.1.3"

[libraries]
# JUnit
junitBom = { module = "org.junit:junit-bom", version.ref = "junit-bom" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher" }
